services:
  redis:
    restart: unless-stopped
    image: redis:7-alpine
    container_name: notification_service_redis
    ports:
      - '6380:6379'
    networks:
      - notification_service_network
    volumes:
      - redis_data:/data 

  task-service:
    restart: unless-stopped
    build: ./task-service
    image: task_service
    container_name: task_service
    ports:
      - '3001:3000'
    volumes:
      - ./task-service:/app
      - /app/node_modules # Keeps container's node_modules separate
    env_file:
      - ./task-service/.env 
    networks:
      - notification_service_network
    depends_on:
      - notification-service

  notification-service:
    restart: unless-stopped
    build: ./notification-service
    image: notification_service
    container_name: notification_service
    ports: 
      - '3000:3000'
    volumes:
      - ./notification-service:/app
      - /app/node_modules # Keeps container's node_modules separate
    env_file:
      - ./notification-service/.env 
    networks:
      - notification_service_network
    depends_on:
      - redis

  worker:
    restart: unless-stopped
    image: notification_service
    container_name: notification_service_worker
    command: npm run worker
    volumes:
      - ./notification-service:/app
      - /app/node_modules
    env_file:
      - ./notification-service/.env 
    networks:
      - notification_service_network
    depends_on:
      - redis
      - notification-service


networks:
  notification_service_network:
    driver: bridge

volumes:
  redis_data: